# This is a basic workflow that is manually triggered

name: Deploy

# Workflow trigger
on:
  push:
    # Inputs the workflow accepts.
    branches: [master]

# Workflow jobs
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ env.MY_VPS_HOST }}
          key: ${{ env.MY_VPS_KEY }}
          username: ${{ env.MY_VPS_USER }}
        
          script: |
            cd /var/www/moblacore.com/
            git pull
            echo 'deploy to Digital Ocean completed'
