# This is a basic workflow that is manually triggered

name: Deploy

# Workflow trigger
on:
  push:
    # Inputs the workflow accepts.
    branches: [master]

# Workflow jobs
jobs:
  deploy:
    environment: VPS_KEY
    env: 
      HOST: ${{ secrets.MY_VPS_HOST }}
      KEY: ${{ secrets.MY_VPS_KEY }}
      USER: ${{ secrets.MY_VPS_USER }}
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ env.HOST }}
          key: ${{ env.KEY }}
          username: ${{ env.USER }}
        
          script: |
            echo user: ${{ secrets.My_VPS_USER }}
            cd /var/www/moblacore.com/
            git pull
            echo 'deploy to Digital Ocean completed'
