# This is a basic workflow that is manually triggered

name: Deploy

# Workflow trigger
on:
  push:
    # Inputs the workflow accepts.
    branches: [main]

# Workflow jobs
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: deploy
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{ secrets.SSH_HOST }}
        key: ${{ secrets.SSH_KEY }}
        username: ${{ secrets.SSH_USERNAME }}
        
        script: |
          cd /var/www/moblacore.com/
          git pull
          echo 'deploy to Digital Ocean completed'
